#!/usr/bin/with-contenv bash

# Copy default config in place and match
# AirVideo Server Computer Name with Container name
[[ ! -e /config/Server.properties ]] && \
  sed -i -e "s/computerName\s*=\s*AirVideoServerHD/computerName = $HOSTNAME/g" /defaults/Server.properties
  cp /defaults/Server.properties /config/Server.properties

# Set permissions
chown -R abc:abc \
  /config /transcode /opt/AirVideoServerHD

# Make sure binary is executable
chmod +x \
  /opt/AirVideoServerHD
